language: node_js
node_js:
  - "10"

install:
  - yarn install

script:
  - yarn build:prod

deploy:
  provider: s3
  access_key_id: "$AWS_KEY"
  secret_access_key: "$AWS_SECRET"
  bucket: "fizzle.tgt101.com"
  local_dir: dist/front-end
  skip_cleanup: true
  on:
    branch: master
